comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true

codecov: 
  token: 9dd0881a-47f3-4c04-8dc6-fedd9dfa8206
